<a href="https://colab.research.google.com/github/ricardoaquiceno/Intro_Pandas_Numpy/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Basics about arrays, index and matrix

In [ ]:
my_list=[1,2,3,5,6,4]
print(my_list)

[1, 2, 3, 5, 6, 4]


In [ ]:
my_nparray=np.array(my_list)
my_npmatrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_npmatrix)
type(my_nparray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
#To index arrays and matrixes
print(my_nparray[2])
print("Matrix index 0,1: ", my_npmatrix[0,1])
print("Matrix index 1,2: ", my_npmatrix[1,2])

3
index 0,1:  2
index 1,2:  6


In [ ]:
#SLICING
arr= np.array([1,2,3,4,5])
print(len(arr))
print(arr[0:2])
print(my_npmatrix[0:2,1:])

5
[1 2]
[[2 3]
 [5 6]]


## Data Types in Numpy


data types can be found here: https://numpy.org/doc/stable/user/basics.types.html

**WARNING: numpy arrays ONLY ACCEPT ONY TYPE OF VARIABLE PER ARRAY. **


In [ ]:
#First, lets see what type is our previously created array
my_list=[1,2,3,5,6,4]
my_nparray=np.array(my_list)
my_nparray.dtype

dtype('int64')

In [ ]:
#We can modify the default type of the array by adding an additional parameter to the function np.array( ) 
new_array=np.array(my_list, dtype="float64")
print(new_array)
print(new_array.dtype)

[1. 2. 3. 5. 6. 4.]
float64


In [ ]:
#we can also modify the type of an already created array
array=np.array([0,1,0,2,3,5,9])
print(array.dtype)
print(array)
array=array.astype(np.float64) #Converting to float 64
print(array.dtype)
print(array)
array=array.astype(np.bool_) #Converting to Booleans: Note that when using Bool, all non zero values are true and only zero values are false. 
print(array.dtype)
print(array)
array=np.array([0,1,0,2,3,5,9])
array=array.astype(np.string_) #Note that when using string, the system transforms to the string representation of the numbers
#Take into account that one cannot convert from a string to an int if the string is not a numeric representation, so 'hola' cannot be converted from 
#string to Int
print(array.dtype)
print(array)


int64
[0 1 0 2 3 5 9]
float64
[0. 1. 0. 2. 3. 5. 9.]
bool
[False  True False  True  True  True  True]
|S21
[b'0' b'1' b'0' b'2' b'3' b'5' b'9']


## Dimensiones


In [ ]:
# We create an scalar wich has dimension 0
scalar= np.array(12)
print(scalar)
scalar.ndim

12


0

In [ ]:
# We create a vector wich has dimension 1
vector= np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
# We create a Matrix wich has dimension 2
matrix= np.array([[1,2,3],[3,4,5]])
print(matrix)
matrix.ndim

[[1 2 3]
 [3 4 5]]


2

In [ ]:
# We create an object wich has dimension 3
#IMPORTANT the amount of squared braces "[]" helps to determine the amount of dimensions when one creates them. see that here at the
#we have np.array([[[.....]]])
threedob= np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(threedob)
threedob.ndim

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


3

ADD or remove dimensions


In [ ]:
#We can create an object with the desired dimentions when declaring it and adding the parameter ndmin=n
vector= np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
#To remove dimensions that we are not using we can use np.squeeze(my_array)
print("vector1 = ", vector)
print(" dim ", vector.ndim)
vector2=np.squeeze(vector)
print("vector2 = ",vector2)
print(" dim ",vector2.ndim)

vector1 =  [[[[[[[[[[1 2 3]]]]]]]]]]
 dim  10
vector2 =  [1 2 3]
 dim  1


In [ ]:
#We can create an object with the desired dimentions when declaring it and adding the parameter ndmin=n
# https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html?highlight=numpy%20expand#numpy.expand_dims
expand= np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

## Creando arrays en Numpy

In [5]:
#As python has range(start, end, step), numpy has np.arange(start,end, step), the difference is that 
# range creates and iterable object and to turn it into a list, we need to cast it like list(py_range)
py_range=range(0,10)
np_arange=np.arange(0,10)
print(py_range)
print(list(py_range))
print(np_arange)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
#ZEROS this is an important function to create matrixes that contain zeros
#IMPORTANT: it receives a tuple () that defines the dimensions (rows,columns,3rddim,4thdim, ndim) 
zeros=np.zeros((2,2,2))
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
#ONES this is an important function to create matrixes that contain ones
#IMPORTANT: it receives a tuple () that defines the dimensions (rows,columns,3rddim,4thdim, ndim) 
ones=np.ones((2,2,2))
ones
twos=2*ones


array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [20]:
#With linspace(start,end,#elements), one can create an array of #elemnts from start to end equaly spaced between them.
a= np.linspace(0,4,3 )
N=8
x1 = np.linspace(0, 10, N, endpoint=True)#the flag endpoint says if the end is inclusive or not, by default is
x2 = np.linspace(0, 10, N, endpoint=False)
print(a)
print(x1)
print(x2)


[0. 2. 4.]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[0.   1.25 2.5  3.75 5.   6.25 7.5  8.75]


In [21]:
#EYE it is a function to generate an identity matrix 2dims, the parameter n=rows=colums as is an identity matrix
identity=np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
#random.rand(rows,columns,3dim...) and random.randint(start,end,(rows,cols,3dim...))
random=np.random.rand(2,3,2)
print(random)
randomint=np.random.randint(1,100,(3,3))
print(randomint)

[[[0.37686704 0.01331657]
  [0.0693115  0.46715222]
  [0.8814954  0.95970342]]

 [[0.00999663 0.3718671 ]
  [0.08890964 0.21264332]
  [0.38764649 0.85706195]]]
[[36  7 63]
 [29 26 71]
 [29 13 71]]


# shape and reshape
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

In [26]:
#shape is a function that helps us to know the dimensions of an array, not the number of dimensions but the amount of rows, columns, 3d and so on
arr= np.random.randint(1,10,(3,3))
print(arr)
print("\n the shape of the array is:", arr.shape)

[[4 7 9]
 [2 6 3]
 [1 5 4]]

 the shape of the array is:  (3, 3)


In [29]:
# on the other hand, reshape allows us to re accommodate the previously mentioned dimensions
arr2=arr.reshape(1,9) #one can directly aply the method reshape to an array 
#one can also call np.reshape(array, (rows,cols...))
arr3=np.reshape(arr2,(9,1))

print(arr2)
print(arr3)



[[4 7 9 2 6 3 1 5 4]]
[[4]
 [7]
 [9]
 [2]
 [6]
 [3]
 [1]
 [5]
 [4]]


In [40]:
#One can re shape with 3 options 'C','F', 'A'
reshapeex=np.random.randint(1,10,(4,3))
print(reshapeex)
print("este es el F \n", reshapeex.reshape(6,2,order='F'))#F is the option to reshape reading through the columns in order
print("este es el C \n", reshapeex.reshape(6,2,order='C'))#C is the option to reshape reading through the rows in order
print("este es el A \n", reshapeex.reshape(6,2,order='A'))# Chooses whichever is the most efficient for the specific environment

[[1 4 6]
 [4 7 6]
 [1 9 1]
 [4 7 7]]
este es el F 
 [[1 9]
 [4 7]
 [1 6]
 [4 6]
 [4 1]
 [7 7]]
este es el C 
 [[1 4]
 [6 4]
 [7 6]
 [1 9]
 [1 4]
 [7 7]]
este es el A 
 [[1 4]
 [6 4]
 [7 6]
 [1 9]
 [1 4]
 [7 7]]
