<a href="https://colab.research.google.com/github/ricardoaquiceno/Intro_Pandas_Numpy/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [1]:
my_list=[1,2,3,5,6,4]
print(my_list)

[1, 2, 3, 5, 6, 4]


In [9]:
my_nparray=np.array(my_list)
my_npmatrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_npmatrix)
type(my_nparray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [14]:
#To index arrays and matrixes
print(my_nparray[2])
print("Matrix index 0,1: ", my_npmatrix[0,1])
print("Matrix index 1,2: ", my_npmatrix[1,2])

3
index 0,1:  2
index 1,2:  6


In [40]:
#SLICING
arr= np.array([1,2,3,4,5])
print(len(arr))
print(arr[0:2])
print(my_npmatrix[0:2,1:])

5
[1 2]
[[2 3]
 [5 6]]
