<a href="https://colab.research.google.com/github/ricardoaquiceno/Intro_Pandas_Numpy/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Basics about arrays, index and matrix

In [ ]:
my_list=[1,2,3,5,6,4]
print(my_list)

[1, 2, 3, 5, 6, 4]


In [ ]:
my_nparray=np.array(my_list)
my_npmatrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_npmatrix)
type(my_nparray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
#To index arrays and matrixes
print(my_nparray[2])
print("Matrix index 0,1: ", my_npmatrix[0,1])
print("Matrix index 1,2: ", my_npmatrix[1,2])

3
index 0,1:  2
index 1,2:  6


In [ ]:
#SLICING
arr= np.array([1,2,3,4,5])
print(len(arr))
print(arr[0:2])
print(my_npmatrix[0:2,1:])

5
[1 2]
[[2 3]
 [5 6]]


## Data Types in Numpy


data types can be found here: https://numpy.org/doc/stable/user/basics.types.html

**WARNING: numpy arrays ONLY ACCEPT ONY TYPE OF VARIABLE PER ARRAY. **


In [ ]:
#First, lets see what type is our previously created array
my_list=[1,2,3,5,6,4]
my_nparray=np.array(my_list)
my_nparray.dtype

dtype('int64')

In [ ]:
#We can modify the default type of the array by adding an additional parameter to the function np.array( ) 
new_array=np.array(my_list, dtype="float64")
print(new_array)
print(new_array.dtype)

[1. 2. 3. 5. 6. 4.]
float64


In [ ]:
#we can also modify the type of an already created array
array=np.array([0,1,0,2,3,5,9])
print(array.dtype)
print(array)
array=array.astype(np.float64) #Converting to float 64
print(array.dtype)
print(array)
array=array.astype(np.bool_) #Converting to Booleans: Note that when using Bool, all non zero values are true and only zero values are false. 
print(array.dtype)
print(array)
array=np.array([0,1,0,2,3,5,9])
array=array.astype(np.string_) #Note that when using string, the system transforms to the string representation of the numbers
#Take into account that one cannot convert from a string to an int if the string is not a numeric representation, so 'hola' cannot be converted from 
#string to Int
print(array.dtype)
print(array)


int64
[0 1 0 2 3 5 9]
float64
[0. 1. 0. 2. 3. 5. 9.]
bool
[False  True False  True  True  True  True]
|S21
[b'0' b'1' b'0' b'2' b'3' b'5' b'9']


## Dimensiones


In [ ]:
# We create an scalar wich has dimension 0
scalar= np.array(12)
print(scalar)
scalar.ndim

12


0

In [ ]:
# We create a vector wich has dimension 1
vector= np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
# We create a Matrix wich has dimension 2
matrix= np.array([[1,2,3],[3,4,5]])
print(matrix)
matrix.ndim

[[1 2 3]
 [3 4 5]]


2

In [ ]:
# We create an object wich has dimension 3
#IMPORTANT the amount of squared braces "[]" helps to determine the amount of dimensions when one creates them. see that here at the
#we have np.array([[[.....]]])
threedob= np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(threedob)
threedob.ndim

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


3

ADD or remove dimensions


In [ ]:
#We can create an object with the desired dimentions when declaring it and adding the parameter ndmin=n
vector= np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
#To remove dimensions that we are not using we can use np.squeeze(my_array)
print("vector1 = ", vector)
print(" dim ", vector.ndim)
vector2=np.squeeze(vector)
print("vector2 = ",vector2)
print(" dim ",vector2.ndim)

vector1 =  [[[[[[[[[[1 2 3]]]]]]]]]]
 dim  10
vector2 =  [1 2 3]
 dim  1


In [ ]:
#We can expand the dimensions of an array with the .expand_dims function 
# https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html?highlight=numpy%20expand#numpy.expand_dims
array= np.array([1,2,3])
expand= np.expand_dims(array,axis=0)
print("array: ", array)
print("expanded array: ",expand)
print(expand.ndim)

array:  [1 2 3]
expanded array:  [[1 2 3]]
2


## Creando arrays en Numpy

In [ ]:
#As python has range(start, end, step), numpy has np.arange(start,end, step), the difference is that 
# range creates and iterable object and to turn it into a list, we need to cast it like list(py_range)
py_range=range(0,10)
np_arange=np.arange(0,10)
print(py_range)
print(list(py_range))
print(np_arange)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#ZEROS this is an important function to create matrixes that contain zeros
#IMPORTANT: it receives a tuple () that defines the dimensions (rows,columns,3rddim,4thdim, ndim) 
zeros=np.zeros((2,2,2))
print(zeros)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
#ONES this is an important function to create matrixes that contain ones
#IMPORTANT: it receives a tuple () that defines the dimensions (rows,columns,3rddim,4thdim, ndim) 
ones=np.ones((2,2,2))
print(ones)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
#With linspace(start,end,#elements), one can create an array of #elemnts from start to end equaly spaced between them.
a= np.linspace(0,4,3 )
N=8
x1 = np.linspace(0, 10, N, endpoint=True)#the flag endpoint says if the end is inclusive or not, by default is
x2 = np.linspace(0, 10, N, endpoint=False)
print(a)
print(x1)
print(x2)


[0. 2. 4.]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[0.   1.25 2.5  3.75 5.   6.25 7.5  8.75]


In [ ]:
#EYE it is a function to generate an identity matrix 2dims, the parameter n=rows=colums as is an identity matrix
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#random.rand(rows,columns,3dim...) and random.randint(start,end,(rows,cols,3dim...))
random=np.random.rand(2,3,2)
print(random)
randomint=np.random.randint(1,100,(3,3))
print(randomint)

[[[0.20774775 0.53695494]
  [0.45284129 0.33183532]
  [0.04488583 0.29292163]]

 [[0.94257438 0.31942715]
  [0.17806263 0.90507159]
  [0.65886084 0.73457219]]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# shape and reshape
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

In [ ]:
#shape is a function that helps us to know the dimensions of an array, not the number of dimensions but the amount of rows, columns, 3d and so on
arr= np.random.randint(1,10,(3,3))
print(arr)
print("\n the shape of the array is:", arr.shape)

[[4 7 9]
 [2 6 3]
 [1 5 4]]

 the shape of the array is:  (3, 3)


In [ ]:
# on the other hand, reshape allows us to re accommodate the previously mentioned dimensions
arr2=arr.reshape(1,9) #one can directly aply the method reshape to an array 
#one can also call np.reshape(array, (rows,cols...))
arr3=np.reshape(arr2,(9,1))

print(arr2)
print(arr3)



[[4 7 9 2 6 3 1 5 4]]
[[4]
 [7]
 [9]
 [2]
 [6]
 [3]
 [1]
 [5]
 [4]]


In [ ]:
#One can re shape with 3 options 'C','F', 'A'
reshapeex=np.random.randint(1,10,(4,3))
print(reshapeex)
print("este es el F \n", reshapeex.reshape(6,2,order='F'))#F is the option to reshape reading through the columns in order
print("este es el C \n", reshapeex.reshape(6,2,order='C'))#C is the option to reshape reading through the rows in order
print("este es el A \n", reshapeex.reshape(6,2,order='A'))# Chooses whichever is the most efficient for the specific environment

[[1 4 6]
 [4 7 6]
 [1 9 1]
 [4 7 7]]
este es el F 
 [[1 9]
 [4 7]
 [1 6]
 [4 6]
 [4 1]
 [7 7]]
este es el C 
 [[1 4]
 [6 4]
 [7 6]
 [1 9]
 [1 4]
 [7 7]]
este es el A 
 [[1 4]
 [6 4]
 [7 6]
 [1 9]
 [1 4]
 [7 7]]


# Funciones principales
https://numpy.org/doc/stable/reference/routines.math.html

https://numpy.org/doc/stable/reference/routines.statistics.html


In [ ]:
arr= np.random.randint(1,20,10)
matriz= arr.reshape(2,5)
print(arr)
print(matriz)

[ 3 11 17  6  8  9 10  9 19 19]
[[ 3 11 17  6  8]
 [ 9 10  9 19 19]]


IMPORTANT, for max,min, argmax. If one uses options for the comparison the vale 0 will always be the comparison of the values from the same position of all the previous dimensions over all the positions of the last dimension
this means, if I have a 3d array, the value 0 will compare the same position i,j for all k, in other words, it will compare the max between

0,0,0 0,0,1 0,0,2 0,0,n and give the max 

0,1,0 0,1,1 0,1,2 0,1,n and give that max 

.

.        .

.          .         .

i,j,0   i,j,1   i,j,2  i,j,n  and give the max of them

Also, take into account that the value 1 will be n-1, meaning that the comparison for a 3d array if i choose the option "1" will be a comparison through the colums and 2 will be a comparison over the rows.

In [ ]:
#.max() helps to find the maximum of an array 
print(arr)
print("max val of arr: ", arr.max())
print(matriz)
print("the max number from the whole matrix is", matriz.max())
print("the max number by rows is", matriz.max(1))#with the option 1 I get the max from each one of the rows as the dimension is 2 and 2-1=1 so gives the comparison of the first dimension
print("the max number by columns is", matriz.max(0))# with the option 0 I get the max from the columns as the dimension is 2 and 2-0=2 so gives the comparison from the 2nd dimension, colums. 

[ 3 11 17  6  8  9 10  9 19 19]
max val of arr:  19
[[ 3 11 17  6  8]
 [ 9 10  9 19 19]]
the max number from the whole matrix is 19
the max number by rows is [17 19]
the max number by columns is [ 9 11 17 19 19]


In [ ]:
# .argmax() if there is no argument, provides the index where the highest value is, taking into account that the index
# corresponds to the most flattened way of the ndarray, meaning the index in 1 dimension. Moreover, if there are 2 values 
# max values, gives the index of the first one found.
trejd=np.random.randint(1,20,(3,3,3))
print(trejd)
print("the index of the max from the object is", trejd.argmax())# gives the argument for the flattened matrix
print("the max number by rows is \n", trejd.max(2))
print("the max number by rows is \n", trejd.max(1))
print("the max number by columns is \n", trejd.max(0))


[[[10 12 19]
  [14 18  1]
  [ 6 19 12]]

 [[ 3 11 16]
  [ 5 15 19]
  [ 4 17 14]]

 [[ 5  5  6]
  [19  1 16]
  [ 2  7 12]]]
the index of the max from the object is 2
the max number by rows is 
 [[19 18 19]
 [16 19 17]
 [ 6 19 12]]
the max number by rows is 
 [[14 19 19]
 [ 5 17 19]
 [19  7 16]]
the max number by columns is 
 [[10 12 19]
 [19 18 19]
 [ 6 19 14]]


In [ ]:
# this is just an example in 4 dimensions to understand the comparisons. 
cuatrod=np.random.randint(1,20,(2,2,2,2))
print(cuatrod)
print("the index of the max from the object is", cuatrod.argmax())# gives the argument for the flattened matrix
print("the max number by rows is \n", cuatrod.max(3))
print("the max number by rows is \n", cuatrod.max(2))
print("the max number by rows is \n", cuatrod.max(1))
print("the max number by columns is \n", cuatrod.max(0))

[[[[13 12]
   [ 1 12]]

  [[ 8  9]
   [ 8 10]]]


 [[[12  6]
   [19  2]]

  [[18  5]
   [14  9]]]]
the index of the max from the object is 10
the max number by rows is 
 [[[13 12]
  [ 9 10]]

 [[12 19]
  [18 14]]]
the max number by rows is 
 [[[13 12]
  [ 8 10]]

 [[19  6]
  [18  9]]]
the max number by rows is 
 [[[13 12]
  [ 8 12]]

 [[18  6]
  [19  9]]]
the max number by columns is 
 [[[13 12]
  [19 12]]

 [[18  9]
  [14 10]]]


In [ ]:
# .min() and .argmin(), opposites of .max() and .argmax()
arr= np.random.randint(1,20,10)
matriz= arr.reshape(2,5)
print(arr)
print("min val of arr: ", arr.min())
print(matriz)
print("the min number from the whole matrix is", matriz.min())
print("the max number by rows is", matriz.min(1))#with the option 1 I get the max from each one of the rows as the dimension is 2 and 2-1=1 so gives the comparison of the first dimension
print("the max number by columns is", matriz.min(0))# with the option 0 I get the max from the columns as the dimension is 2 and 2-0=2 so gives the comparison from the 2nd dimension, colums. 

[14  9  6 18 17  6 11  4 17  2]
min val of arr:  2
[[14  9  6 18 17]
 [ 6 11  4 17  2]]
the min number from the whole matrix is 2
the max number by rows is [6 2]
the max number by columns is [ 6  9  4 17  2]


In [ ]:
# .ptp() gives the distance between the minimum and the maximum of an ndarray
print("this is the arr:\n ",arr)
print("ptp: ", arr.ptp())
print("\n this is the mtrix: \n",matriz)
print("ptp by rows: ",matriz.ptp(1))
print("ptp by cols: ", matriz.ptp(0))

this is the arr:
  [14  9  6 18 17  6 11  4 17  2]
ptp:  16

 this is the mtrix: 
 [[14  9  6 18 17]
 [ 6 11  4 17  2]]
ptp by rows:  [12 15]
ptp by cols:  [ 8  2  2  1 15]


In [ ]:
#Some functions for statistics: np.percentile(ndarr,percentile),  .sort(), np.median(arr), np.std(), np.var(), np.mean()
arr= np.random.randint(1,20,10)
print(arr)
print("percentile: ", np.percentile(arr,40))
arr.sort() #built in function that sorts the specific array, this cannot be assigned to another array, if one needs to assign it to another array, 
          #one must copy arr
print("sorted array: \n", arr) 
print("median: ",np.median(arr)) # finds the median of an array
print("std deviation: ", np.std(arr))# finds the standard deviation of an ndarray
print("variance: ", np.var(arr))# finds the variance deviation of an ndarray
print("mean: ", np.mean(matriz,0))# finds the mean of an ndarray


[18 19 18 11 17  9  3 19 17  2]
percentile:  14.600000000000001
sorted array: 
 [ 2  3  9 11 17 17 18 18 19 19]
median:  17.0
std deviation:  6.277738446287803
variance:  39.410000000000004
mean:  [10.  10.   5.  17.5  9.5]


In [ ]:
# concatenate(a,b) helps to concatanate arrays, one must meet the criteria to appropriately concatanate
# the rules are the dimensions, if one wants to concatenate to an 2x3 matrix, the array to concatenate must be of dimension 2 (matrix) 
# and size 1x3 for axis=0, or dimension=2 and size 2x1 for axis=1
#WARNING I cannot concatenate an array to a matrix, thats why b and c are declared as matrixes, cause dimensions as well as size must agree
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[1,7,8]])
c= np.array([[9],[10]])
print(a)
print(np.concatenate((a,b),axis=0)) # here I am concatanating another row (axis=0)
print(np.concatenate((a,c),axis=1)) # here I am concatenating another column (axis=1)

[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]
 [1 7 8]]
[[ 1  2  3  9]
 [ 3  4  5 10]]


In [ ]:
# .T this function gives the transpose of a matrix
a=np.array([[1,2,3],[3,4,5]])
aT= a.T
print(a,"\n")
print(aT)

[[1 2 3]
 [3 4 5]] 

[[1 3]
 [2 4]
 [3 5]]


#Copy
Copy is a really important comand as python internally does not create automatic copies, this means, if I create a matrix "a" and then I assign to another variable "b", an slice of the main matrix, whenever I modify that variable b, I am modifying "a" as pythons is pointing to the same memory space, here is where copy comes handy. 

In [ ]:
a=np.array([[1,2],[3,4]])
b=a[0,:]
print("this is a prio modifying b: \n",a)
print("this is b: ", b)
b[0]=2
print("this is a after modifying b: \n",a) #as you can see, I am modifying b but a gets modified

this is a prio modifying b: 
 [[1 2]
 [3 4]]
this is b:  [1 2]
this is a after modifying b: 
 [[1 2]
 [3 4]]


In [ ]:
a=np.array([[1,2],[3,4]])
ac=a.copy()
b=ac[0,:]
print("this is a prio modifying b: \n",a)
print("this is b: ", b)
b[0]=2
print("this is b modified: ", b)
print("this is a after modifying b: \n",a) #as you can see, using copy we dont get the original a modified

this is a prio modifying b: 
 [[1 2]
 [3 4]]
this is b:  [1 2]
this is b modified:  [2 2]
this is a after modifying b: 
 [[1 2]
 [3 4]]


#Conditions
One can make conditions directly in the indexing of the arrays, this is really useful to make fast flterings

In [ ]:
a=np.linspace(1,8,8)
print(a)
b=a[a>6]
print(b)
a[a==1]=3
print(a)
b=a[(a>4)&(a<7)]
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]
[7. 8.]
[3. 2. 3. 4. 5. 6. 7. 8.]
[5. 6.]


#Operaciones
In numpy, when one aplies arithmetic operations to an array, it works directly to each of the values of the array, so if I want to sum x value I just have to do arr + x and all the individual values of arr will be summed with x. same with different operations. 
Please note that this is not always possible with python lists 

In [ ]:
milist= list([1,2,3,4])
print(milist*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()
print(arr * 2)
print(arr + 2)
print(1 / arr )
print(arr ** 2)
print(arr + arr2)
print(arr - arr2)
print(arr * arr2)


[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[ 0  1  4  9 16 25 36 49 64 81]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
print(matriz)
print(matriz + matriz2)
print(matriz - matriz2)
print(matriz2.T)
print(np.matmul(matriz,matriz2.T)) # this is the dot product 
print(matriz @ matriz2.T)# this is the dot product in a different sintaxis. 


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
