<a href="https://colab.research.google.com/github/ricardoaquiceno/Intro_Pandas_Numpy/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

## Basics about arrays, index and matrix

In [ ]:
my_list=[1,2,3,5,6,4]
print(my_list)

[1, 2, 3, 5, 6, 4]


In [ ]:
my_nparray=np.array(my_list)
my_npmatrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_npmatrix)
type(my_nparray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
#To index arrays and matrixes
print(my_nparray[2])
print("Matrix index 0,1: ", my_npmatrix[0,1])
print("Matrix index 1,2: ", my_npmatrix[1,2])

3
index 0,1:  2
index 1,2:  6


In [ ]:
#SLICING
arr= np.array([1,2,3,4,5])
print(len(arr))
print(arr[0:2])
print(my_npmatrix[0:2,1:])

5
[1 2]
[[2 3]
 [5 6]]


### Data Types in Numpy

data types can be found here: https://numpy.org/doc/stable/user/basics.types.html

**WARNING: numpy arrays ONLY ACCEPT ONY TYPE OF VARIABLE PER ARRAY. **


In [4]:
#First, lets see what type is our previously created array
my_list=[1,2,3,5,6,4]
my_nparray=np.array(my_list)
my_nparray.dtype

dtype('int64')

In [5]:
#We can modify the default type of the array by adding an additional parameter to the function np.array( ) 
new_array=np.array(my_list, dtype="float64")
print(new_array)
print(new_array.dtype)

[1. 2. 3. 5. 6. 4.]
float64


In [10]:
#we can also modify the type of an already created array
array=np.array([0,1,0,2,3,5,9])
print(array.dtype)
print(array)
array=array.astype(np.float64) #Converting to float 64
print(array.dtype)
print(array)
array=array.astype(np.bool_) #Converting to Booleans: Note that when using Bool, all non zero values are true and only zero values are false. 
print(array.dtype)
print(array)
array=np.array([0,1,0,2,3,5,9])
array=array.astype(np.string_) #Note that when using string, the system transforms to the string representation of the numbers
#Take into account that one cannot convert from a string to an int if the string is not a numeric representation, so 'hola' cannot be converted from 
#string to Int
print(array.dtype)
print(array)


int64
[0 1 0 2 3 5 9]
float64
[0. 1. 0. 2. 3. 5. 9.]
bool
[False  True False  True  True  True  True]
|S21
[b'0' b'1' b'0' b'2' b'3' b'5' b'9']
